package org.slim.ui;

import com.slim.ui.pageOblectClasses.DashboardPage;
import com.slim.ui.pageOblectClasses.LoginPage;
import com.slim.ui.pageOblectClasses.Overview.OverviewPage;
import com.slim.ui.pageOblectClasses.office.OfficePage;
import com.slim.ui.pageOblectClasses.planning.PlanningPage;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import static com.codeborne.selenide.Selenide.sleep;
import static com.slim.ui.dataGenerator.DataGenerator.getTime;

public class FirstPlanningSecondUpdate extends BaseTest {

    DashboardPage dashboardPage = new DashboardPage();
    LoginPage loginPage = new LoginPage();
    OfficePage officePage = new OfficePage();
    PlanningPage planningPage = new PlanningPage();
    OverviewPage overviewPage = new OverviewPage();

    @BeforeClass

    private void preClass() {
        loginPage
                .loginToDashboard("anastasia@fitsoft.nl", "QWEqwe123!@#");
    }
    @Test(enabled = false)
    public void updateTest() {
        dashboardPage
                .openDashBoard()
                .clickOverviewButton();
        overviewPage
                .clickFirstPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickOKButton()
                .clickSecondPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickOKButton();
    }
    /* Without BackToEditing*/

    @Test(enabled = false)
    private void Script_2_AABB() {
        dashboardPage
                .openDashBoard()
                .clickPlanningButton();
        planningPage
                .chooseDateofPlansheet()
                .clickEditPlansheetButton()
                .deleteNewTrips()
                .clickRandomNewTripButton()
                .checkLicenses()
                .clickGoToPlanningButton()
                .clickDeleteAttachingTrailerButton()
                .clickDeleteDetachingTrailerButton()
                .changeAddresses()
                .dragShipment()
               // .inputTimeToFirstFromUntilTime(getTime(10,11), getTime(14,15))
                .clickCalculateTripButton()
                .clickOKButtonOnWarningPopUp()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickYesButton()
                .clickOverviewButton();
        overviewPage
                .clickSecondPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickOKButton();
    }
    @Test(enabled = false)
    private void Script_2_ABBA() {
        dashboardPage
                .openDashBoard()
                .clickPlanningButton();
        planningPage
                .chooseDateofPlansheet()
                .clickEditPlansheetButton()
                .deleteNewTrips()
                .clickRandomNewTripButton()
                .checkLicenses()
                .clickGoToPlanningButton()
                .clickDeleteAttachingTrailerButton()
                .clickDeleteDetachingTrailerButton()
                .changeAddresses()
                .dragShipment()
                .inputTimeToFirstFromUntilTime(getTime(10,11), getTime(14,15))
                .clickCalculateTripButton()
                .clickOKButtonOnWarningPopUp()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickOverviewButton();
        overviewPage
                .clickSecondPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickOKButton()
                .clickPlanningPagebutton();
        planningPage
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickYesButton();
    }
    @Test(enabled = false)
    private void Script_2_AB3AB() {
        dashboardPage
                .openDashBoard()
                .clickPlanningButton();
        planningPage
                .chooseDateofPlansheet()
                .clickEditPlansheetButton()
                .deleteNewTrips()
                .clickRandomNewTripButton()
                .checkLicenses()
                .clickGoToPlanningButton()
                .clickDeleteAttachingTrailerButton()
                .clickDeleteDetachingTrailerButton()
                .changeAddresses()
                .dragShipment()
                .inputTimeToFirstFromUntilTime(getTime(10,11), getTime(14,15))
                .clickCalculateTripButton()
                .clickOKButtonOnWarningPopUp()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickOverviewButton();
        overviewPage
                .clickFirstPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickCloseButtonFirstWindow()
                .clickProceedButton()
                .clickPlanningPagebutton();
        planningPage
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickYesButton()
                .clickOverviewButton();
        overviewPage
                .clickSecondPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickOKButton()
                .clickPlanningPagebutton();
    }
    /*BackToEditing/Cancel one*/
    //A1A (Calculate/BackToEditing/Calculate one)
    @Test(enabled = false)
    private void Script_2_A1A_B3ABB() {
        dashboardPage
                .openDashBoard()
                .clickPlanningButton();
        planningPage
                .chooseDateofPlansheet()
                .clickEditPlansheetButton()
                .deleteNewTrips()
                .clickRandomNewTripButton()
                .checkLicenses()
                .clickGoToPlanningButton()
                .clickDeleteAttachingTrailerButton()
                .clickDeleteDetachingTrailerButton()
                .changeAddresses()
                .dragShipment()
                .inputTimeToFirstFromUntilTime(getTime(10, 11), getTime(14, 15))
                .clickCalculateTripButton()
                .clickOKButtonOnWarningPopUp()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickBackToEditingButton()
                .clickCalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickOverviewButton();
        overviewPage
                .clickFirstPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickCloseButtonFirstWindow()
                .clickProceedButton()
                .clickPlanningPagebutton();
        planningPage
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickYesButton()
                .clickOverviewButton();
        overviewPage
                .clickSecondPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickOKButton()
                .clickPlanningPagebutton();
    }
    @Test(enabled = false)
    private void Script_2_A1A_BBA() {
        dashboardPage
                .openDashBoard()
                .clickPlanningButton();
        planningPage
                .chooseDateofPlansheet()
                .clickEditPlansheetButton()
                .deleteNewTrips()
                .clickRandomNewTripButton()
                .checkLicenses()
                .clickGoToPlanningButton()
                .clickDeleteAttachingTrailerButton()
                .clickDeleteDetachingTrailerButton()
                .changeAddresses()
                .dragShipment()
                .inputTimeToFirstFromUntilTime(getTime(10, 11), getTime(14, 15))
                .clickCalculateTripButton()
                .clickOKButtonOnWarningPopUp()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickBackToEditingButton()
                .clickCalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickOverviewButton();
        overviewPage
                .clickFirstPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickOKButton()
                .clickPlanningPagebutton();
        planningPage
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickYesButton();
    }
    @Test(enabled = false)
    private void Script_2_A1A_ABB() {
        dashboardPage
                .openDashBoard()
                .clickPlanningButton();
        planningPage
                .chooseDateofPlansheet()
                .clickEditPlansheetButton()
                .deleteNewTrips()
                .clickRandomNewTripButton()
                .checkLicenses()
                .clickGoToPlanningButton()
                .clickDeleteAttachingTrailerButton()
                .clickDeleteDetachingTrailerButton()
                .changeAddresses()
                .dragShipment()
                .inputTimeToFirstFromUntilTime(getTime(10, 11), getTime(14, 15))
                .clickCalculateTripButton()
                .clickOKButtonOnWarningPopUp()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickBackToEditingButton()
                .clickCalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickYesButton()
                .clickOverviewButton();
        overviewPage
                .clickSecondPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickOKButton();
    }
    //A1B (Calculate/BacktoEditing one, ReCalculate other)
    @Test(enabled = false)
    private void Script_2_A1B_3AABB() {
        dashboardPage
                .openDashBoard()
                .clickPlanningButton();
        planningPage
                .chooseDateofPlansheet()
                .clickEditPlansheetButton()
                .deleteNewTrips()
                .clickRandomNewTripButton()
                .checkLicenses()
                .clickGoToPlanningButton()
                .clickDeleteAttachingTrailerButton()
                .clickDeleteDetachingTrailerButton()
                .changeAddresses()
                .dragShipment()
                .inputTimeToFirstFromUntilTime(getTime(10, 11), getTime(14, 15))
                .clickCalculateTripButton()
                .clickOKButtonOnWarningPopUp()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickBackToEditingButton()
                .clickOverviewButton();
        overviewPage
                .clickFirstPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickCloseButtonFirstWindow()
                .clickProceedButton()
                .clickPlanningPagebutton();
        planningPage
                .clickCalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickYesButton()
                .clickOverviewButton();
        overviewPage
                .clickSecondPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickOKButton();
    }
    @Test(enabled = false)
    private void Script_2_A1B_3ABBA() {
        dashboardPage
                .openDashBoard()
                .clickPlanningButton();
        planningPage
                .chooseDateofPlansheet()
                .clickEditPlansheetButton()
                .deleteNewTrips()
                .clickRandomNewTripButton()
                .checkLicenses()
                .clickGoToPlanningButton()
                .clickDeleteAttachingTrailerButton()
                .clickDeleteDetachingTrailerButton()
                .changeAddresses()
                .dragShipment()
                .inputTimeToFirstFromUntilTime(getTime(10, 11), getTime(14, 15))
                .clickCalculateTripButton()
                .clickOKButtonOnWarningPopUp()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickBackToEditingButton()
                .clickOverviewButton();
        overviewPage
                .clickFirstPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickCloseButtonFirstWindow()
                .clickProceedButton()
                .clickPlanningPagebutton();
        planningPage
                .clickCalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickOverviewButton();
        overviewPage
                .clickSecondPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickOKButton()
                .clickPlanningPagebutton();
        planningPage
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickYesButton();
    }
    @Test(enabled = false)
    private void Script_2_A1B_BBA() {
        dashboardPage
                .openDashBoard()
                .clickPlanningButton();
        planningPage
                .chooseDateofPlansheet()
                .clickEditPlansheetButton()
                .deleteNewTrips()
                .clickRandomNewTripButton()
                .checkLicenses()
                .clickGoToPlanningButton()
                .clickDeleteAttachingTrailerButton()
                .clickDeleteDetachingTrailerButton()
                .changeAddresses()
                .dragShipment()
                .inputTimeToFirstFromUntilTime(getTime(10, 11), getTime(14, 15))
                .clickCalculateTripButton()
                .clickOKButtonOnWarningPopUp()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickBackToEditingButton()
                .clickOverviewButton();
        overviewPage
                .clickFirstPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickOKButton()
                .clickPlanningPagebutton();
        planningPage
                .clickCalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickYesButton();
    }
    //AB31 (Calculate one, ReCalculate/Cancel other, BackToEditing one)
    @Test(enabled = false)
    private void Script_2_AB31_ABBA() {
        dashboardPage
                .openDashBoard()
                .clickPlanningButton();
        planningPage
                .chooseDateofPlansheet()
                .clickEditPlansheetButton()
                .deleteNewTrips()
                .clickRandomNewTripButton()
                .checkLicenses()
                .clickGoToPlanningButton()
                .clickDeleteAttachingTrailerButton()
                .clickDeleteDetachingTrailerButton()
                .changeAddresses()
                .dragShipment()
                .inputTimeToFirstFromUntilTime(getTime(10, 11), getTime(14, 15))
                .clickCalculateTripButton()
                .clickOKButtonOnWarningPopUp()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickOverviewButton();
        overviewPage
                .clickFirstPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickCloseButtonFirstWindow()
                .clickProceedButton()
                .clickPlanningPagebutton();
        planningPage
                .clickBackToEditingButton()
                .clickCalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickOverviewButton();
        overviewPage
                .clickFirstPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickOKButton()
                .clickPlanningPagebutton();
        planningPage
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickYesButton();
    }
    @Test(enabled = false)
    private void Script_2_AB31_AABB() {
        dashboardPage
                .openDashBoard()
                .clickPlanningButton();
        planningPage
                .chooseDateofPlansheet()
                .clickEditPlansheetButton()
                .deleteNewTrips()
                .clickRandomNewTripButton()
                .checkLicenses()
                .clickGoToPlanningButton()
                .clickDeleteAttachingTrailerButton()
                .clickDeleteDetachingTrailerButton()
                .changeAddresses()
                .dragShipment()
                .inputTimeToFirstFromUntilTime(getTime(10, 11), getTime(14, 15))
                .clickCalculateTripButton()
                .clickOKButtonOnWarningPopUp()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickOverviewButton();
        overviewPage
                .clickFirstPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickCloseButtonFirstWindow()
                .clickProceedButton()
                .clickPlanningPagebutton();
        planningPage
                .clickBackToEditingButton()
                .clickCalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickYesButton()
                .clickOverviewButton();
        overviewPage
                .clickSecondPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickOKButton()
                .clickPlanningPagebutton();
    }
    @Test(enabled = false)
    private void Script_2_AB31_BBAA() {
        dashboardPage
                .openDashBoard()
                .clickPlanningButton();
        planningPage
                .chooseDateofPlansheet()
                .clickEditPlansheetButton()
                .deleteNewTrips()
                .clickRandomNewTripButton()
                .checkLicenses()
                .clickGoToPlanningButton()
                .clickDeleteAttachingTrailerButton()
                .clickDeleteDetachingTrailerButton()
                .changeAddresses()
                .dragShipment()
                .inputTimeToFirstFromUntilTime(getTime(10, 11), getTime(14, 15))
                .clickCalculateTripButton()
                .clickOKButtonOnWarningPopUp()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickOverviewButton();
        overviewPage
                .clickFirstPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickCloseButtonFirstWindow()
                .clickProceedButton()
                .clickPlanningPagebutton();
        planningPage
                .clickBackToEditingButton()
                .clickOverviewButton();
        overviewPage
                .clickFirstPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickOKButton()
                .clickPlanningPagebutton();
        planningPage
                .clickCalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickYesButton();
    }
    //AB2 (Calculate one, ReCalculate/BackToEditing or Cancel other)
    @Test(enabled = false)
    private void Script_2_AB2_BBA() {
        dashboardPage
                .openDashBoard()
                .clickPlanningButton();
        planningPage
                .chooseDateofPlansheet()
                .clickEditPlansheetButton()
                .deleteNewTrips()
                .clickRandomNewTripButton()
                .checkLicenses()
                .clickGoToPlanningButton()
                .clickDeleteAttachingTrailerButton()
                .clickDeleteDetachingTrailerButton()
                .changeAddresses()
                .dragShipment()
                .inputTimeToFirstFromUntilTime(getTime(10,11), getTime(14,15))
                .clickCalculateTripButton()
                .clickOKButtonOnWarningPopUp()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickOverviewButton();
        overviewPage
                .clickSecondPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickBackToEditingR()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickOKButton()
                .clickPlanningPagebutton();
        planningPage
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickYesButton();
    }
    @Test(enabled = false)
    private void Script_2_AB2_B3ABB() {
        dashboardPage
                .openDashBoard()
                .clickPlanningButton();
        planningPage
                .chooseDateofPlansheet()
                .clickEditPlansheetButton()
                .deleteNewTrips()
                .clickRandomNewTripButton()
                .checkLicenses()
                .clickGoToPlanningButton()
                .clickDeleteAttachingTrailerButton()
                .clickDeleteDetachingTrailerButton()
                .changeAddresses()
                .dragShipment()
                .inputTimeToFirstFromUntilTime(getTime(10,11), getTime(14,15))
                .clickCalculateTripButton()
                .clickOKButtonOnWarningPopUp()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickOverviewButton();
        overviewPage
                .clickFirstPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickBackToEditingR()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickCloseButtonFirstWindow()
                .clickProceedButton()
                .clickPlanningPagebutton();
        planningPage
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickYesButton()
                .clickOverviewButton();
        overviewPage
                .clickSecondPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickOKButton();
    }
    @Test(enabled = false)
    private void Script_2_AB2_3ABB() {
        dashboardPage
                .openDashBoard()
                .clickPlanningButton();
        planningPage
                .chooseDateofPlansheet()
                .clickEditPlansheetButton()
                .deleteNewTrips()
                .clickRandomNewTripButton()
                .checkLicenses()
                .clickGoToPlanningButton()
                .clickDeleteAttachingTrailerButton()
                .clickDeleteDetachingTrailerButton()
                .changeAddresses()
                .dragShipment()
                .inputTimeToFirstFromUntilTime(getTime(10,11), getTime(14,15))
                .clickCalculateTripButton()
                .clickOKButtonOnWarningPopUp()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickOverviewButton();
        overviewPage
                .clickFirstPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickBackToEditingR()
                .clickCloseButtonFirstWindow()
                .clickProceedButton()
                .clickPlanningPagebutton();
        planningPage
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickYesButton()
                .clickOverviewButton();
        overviewPage
                .clickSecondPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickOKButton();
    }
    @Test(enabled = false)
    private void Script_2_AB3_ABB() {
        dashboardPage
                .openDashBoard()
                .clickPlanningButton();
        planningPage
                .chooseDateofPlansheet()
                .clickEditPlansheetButton()
                .deleteNewTrips()
                .clickRandomNewTripButton()
                .checkLicenses()
                .clickGoToPlanningButton()
                .clickDeleteAttachingTrailerButton()
                .clickDeleteDetachingTrailerButton()
                .changeAddresses()
                .dragShipment()
                .inputTimeToFirstFromUntilTime(getTime(10,11), getTime(14,15))
                .clickCalculateTripButton()
                .clickOKButtonOnWarningPopUp()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickOverviewButton();
        overviewPage
                .clickFirstPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickCloseButtonFirstWindow()
                .clickProceedButton()
                .clickPlanningPagebutton();
        planningPage
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickYesButton()
                .clickOverviewButton();
        overviewPage
                .clickSecondPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickOKButton();
    }
    //AAB2
    @Test(enabled = false)
    private void Script_2_AAB3_BB() {
        dashboardPage
                .openDashBoard()
                .clickPlanningButton();
        planningPage
                .chooseDateofPlansheet()
                .clickEditPlansheetButton()
                .deleteNewTrips()
                .clickRandomNewTripButton()
                .checkLicenses()
                .clickGoToPlanningButton()
                .clickDeleteAttachingTrailerButton()
                .clickDeleteDetachingTrailerButton()
                .changeAddresses()
                .dragShipment()
                .inputTimeToFirstFromUntilTime(getTime(10,11), getTime(14,15))
                .clickCalculateTripButton()
                .clickOKButtonOnWarningPopUp()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickYesButton()
                .clickOverviewButton();
        overviewPage
                .clickSecondPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickCloseButtonFirstWindow()
                .clickProceedButton()
                .clickSecondPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickOKButton();
    }
    //AAB1
    @Test(enabled = false)
    private void Script_2_AAB1_AA() {
        dashboardPage
                .openDashBoard()
                .clickPlanningButton();
        planningPage
                .chooseDateofPlansheet()
                .clickEditPlansheetButton()
                .deleteNewTrips()
                .clickRandomNewTripButton()
                .checkLicenses()
                .clickGoToPlanningButton()
                .clickDeleteAttachingTrailerButton()
                .clickDeleteDetachingTrailerButton()
                .changeAddresses()
                .dragShipment()
                .inputTimeToFirstFromUntilTime(getTime(10,11), getTime(14,15))
                .clickCalculateTripButton()
                .clickOKButtonOnWarningPopUp()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButton()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickYesButton()
                .clickOverviewButton();
        overviewPage
                .clickSecondPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickCloseButtonFirstWindow()
                .clickProceedButton()
                .clickSecondPlannedTrip()
                .clickTripUpdate()
                .clickRecalculateTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickTripDetailsButton()
                .clickResultsTab()
                .clickCloseButtonSecondWindow()
                .clickPublishTripButton()
                .clickIUnderstandButtonOnWarningPopUp()
                .clickOKButton();
    }
}

